### ISSUE TITLE
SpamExperts no longer loading

### ISSUE THREAD

**Issue by sempiterna** [SpamExperts/zimbra-addon#7]
Zimbra version: 8.7.11

The SpamExperts zimbra addon is, since earlier this week, no longer loading. This is the error message I receive when checking with Firebug:

`Load denied by X-Frame-Options: https://api.antispamcloud.com/spampanel.php#/dashboard does not permit cross-origin framing.`

It seems spamexperts changed something on their webserver to disallow loading inside a frame.

The zimlet version I am using is 1.0. I'm unable to update to 1.2 due to the following error:

`java.io.FileNotFoundException: zimlet description not found: com_zimbra_spamexperts.xml
        at com.zimbra.cs.zimlet.ZimletFile.initZimletDescription(ZimletFile.java:267)
        at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:223)
        at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:175)
        at com.zimbra.cs.zimlet.ZimletFile.<init>(ZimletFile.java:156)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1905)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2007)`

`[] ERROR: Error`

`java.io.FileNotFoundException: zimlet description not found: com_zimbra_spamexperts.xml
        at com.zimbra.cs.zimlet.ZimletFile.initZimletDescription(ZimletFile.java:267)
        at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:223)
        at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:175)
        at com.zimbra.cs.zimlet.ZimletFile.<init>(ZimletFile.java:156)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1905)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2007)
`

**Comment by dmitry-lomakin** [comment]
To improve Spampanel security an ability to send `X-Frame-Options` header was added. The protection was enabled by default on the SpamExperts' Hosted Cloud (`*.antispamcloud.com`). Since Zimbra loads Spampanel in an iframe on a different host and that's why the browser rejects opening the page.

In order to fix things some changes on the admin account who uses Spampanel are required. In particular, the admin should log in, go to the Server -> Setting page and under the "Protection against rendering in HTML Frames" section select either "No protection" option (not recommended) or "Allow from URL" and enter your hostname where Zimbra works. After saving the changes things should start working for you again.

We apology for any inconvenience caused by that change.

**Comment by sempiterna** [comment]
I'm a "Domain User", so I probably do not have access to that feature. Isn't antispamcloud.com run by SpamExperts? If that's the case then SpamExperts is the probably the admin?.

Also, to get around this issue, maybe it is an idea to have a setting that allows to load the spampanel in a new frame/window? Since now it can't be used by anyone using the hosted service.

**Comment by dmitry-lomakin** [comment]
> I'm a "Domain User", so I probably do not have access to that feature.

This is correct - only users with `admin` role have access to that setting.

> Isn't antispamcloud.com run by SpamExperts?

SpamExperts manages server-wide defaults at antispamcloud.com by many settings (including the "Protection against rendering in HTML Frames" one) can be redefined by admins who uses and control usage of the spam filtering services.

> Also, to get around this issue, maybe it is an idea to have a setting that allows to load the spampanel in a new frame/window?

Such setting is already available - as explained before, the admin whom credentials are used for Zimbra configuration should access Spampanel, go to the Server -> Setting page and under the "Protection against rendering in HTML Frames" section select either "No protection" option (not recommended) or "Allow from URL" and enter your hostname where Zimbra works. After saving the changes things should start working again.

Please let me know if something is not clear still or things don't work for you even after following the steps that I suggested.

**Comment by sempiterna** [comment]
I think we misunderstand eachother. I am the root administrator of the Zimbra server, but only have "Domain User" access on the spampanel (which is hosted by SpamExperts).  My question was if the SpamExperts zimbra plugin (the plugin, not spamexperts itself) can have a configurable setting that allows for the spampanel to load in a new window/tab instead of inside a frame. So basically when you click the SpamExperts link in the Zimbra webinterface, a new window or tab opens which contains the spampanel.

That way people (like myself) who are Zimbra admins, but have no admin access on the externally hosted antispamcloud, can still use the plugin. Right now, since SpamExperts made this change, this plugin is only useful to report spam and not much else. Which is very unfortunate, because it was incredibly useful for my mail users to check if some mail was tagged as spam and not delivered.

**Comment by tonyandrewmeyer** [comment]
Sorry for the confusion here. There was a bug with the SpamExperts control panel (internal bug ID #33332) that meant that the protection was wrongly applied in some cases. This is almost certainly what happened to you.

The antispamcloud.com Hosted Cloud will get the fix for this bug today, roughly 12 hours from now. My expectation is that this will solve the problem for you.

The comments from @for93t above are correct if the admin did actually enable protection - but it seems more likely that didn't happen, and you unfortunately hit this bug instead. We are very sorry for the inconvenience, of course, and are looking into how this managed to slip through our QA processes.

If it isn't solved later today, then the best course would be to contact your SpamExperts provider to check whether they did enable protection, or to get them to open a feature request for the new tab behaviour you suggest above. Or, if you're a direct client, then just email support@spamexperts.com (or open a ticket directly in the support system) and our support team should be able to resolve this quickly.

**Comment by sempiterna** [comment]
I'm happy to confirm that it is working again. Thank you for fixing this.

**Comment by MisTerM7** [comment]
> In order to fix things some changes on the admin account who uses Spampanel are required. In particular, the admin should log in, go to the Server -> Setting page and under the "Protection against rendering in HTML Frames" section select either "No protection" option (not recommended) or "Allow from URL" and enter your hostname where Zimbra works. After saving the changes things should start working for you again.
> 
> We apology for any inconvenience caused by that change.

I use the version 1.2 is I have the same error as the later version, do you have a tutorial to bypassed this error is so I can install finally this addon is running SpamExpert for my Zimbra license please thank you
